### ISSUE TITLE
NFT Support 

### ISSUE THREAD

**Issue by frostweb3** [skalenetwork/metaport#36] opened 2022-08-23 21:10 UTC
Metaport currently does not have NFT support.   

From a technical perspective this can be supported after discussing it in further detail with engineering / D1 

We have the required functions in IMA-JS, 

Thoughts need to be discussed on the UI. 

Benefits the ecosystem/skaleverse eg gaming dapps who have launched and also have NFTs to release that require moving between S2S

**Comment by dmytrotkk** [comment] 2022-08-25 16:13
@cstrangedk @SKALE-jace @gannakulikova let's schedule a meeting to discuss 🤔

**Comment by frostweb3** [comment] 2022-08-26 23:52
Notes from August 26th meeting

Widget Metaport NFT Support 
- a simplified view that will display source and destination chain, ETH triangle 721/1155, nft name/family and token ID, 
- trigger transfer by outside application, buttons for each nft,

Needs investigation
1. Images from one chain to another - transfer will stay on 1 or move to 2 (fetch token contract, which contract address. Investigate but is it an option to see/pull all token IDs on contracts) need to discuss with D3 with block explorer/token ID to index or pull API, 
2. Pull and source of images (whom to handle it) ie store a link to an image? pull from URI

D1 will prepare a demo and section for NFTs

**Comment by cstrangedk** [comment] 2022-10-08 00:02
duplicate of #47

**Closed as not planned by cstrangedk** 2022-10-08 00:02 UTC
Labels: enhancement
